app:
  c3p0:
    datasource: 
      jdbc-url: jdbc:h2:mem:bm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      user: sa
      password: 
      driver-class: org.h2.Driver
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true