app:
  c3p0:
    datasource: 
      jdbc-url: jdbc:mysql://${OPENSHIFT_MYSQL_DB_HOST}:${OPENSHIFT_MYSQL_DB_PORT}/${OPENSHIFT_APP_NAME}?useSSL=false
      user: ${OPENSHIFT_MYSQL_DB_USERNAME}
      password: ${OPENSHIFT_MYSQL_DB_PASSWORD} 
      driver-class: com.mysql.jdbc.Driver
spring:
  profiles:
    active: pro
  jpa: 
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      show-sql: false
logging:
  config: classpath:logback-pro.xml